.Dd bytepusher\-VERSION
.Dt BYTEPUSHER 1
.Os
.Sh NAME
.Nm bytepusher
.Nd a Bytepusher VM implementation
.Sh SYNOPSIS
.Nm
.Op rom
.Sh DESCRIPTION
.Nm
reads a Bytepusher source file and executes it. It
uses the SDL2 library as a rendering API.
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@margiolis.net
