.Dd minecurses\-VERSION
.Dt MINECURSES 6
.Os
.Sh NAME
.Nm minecurses
.Nd a terminal minesweeper game
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
starts a minesweeper game using the
.Xr ncurses 3
library to draw the TUI.
.Sh OPTIONS
The following option are used during runtime in the TUI,
not the command line.
.Bl -tag -width 8n
.It Sy q
quit game
.It Sy r
restart game
.It Sy w/k
move up on the Y axis
.It Sy s/j
move down on the Y axis
.It Sy a/h
move left on the X axis
.It Sy d/l
move right on the X axis
.It Sy f
flag cell
.It Sy g
defuse mine (if flagged only)
.It Sy ENTER/o
open cell
.Sh SEE ALSO
.Xr ncurses 3
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@christosmarg.xyz
