.Dd minecurses\-VERSION
.Dt MINECURSES 6
.Os
.Sh NAME
.Nm minecurses
.Nd a terminal minesweeper game
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
starts a 
.Xr curses 3
minesweeper game. The objective is to find and defuse all the mines,
not open all the non-mine cells, like in most minesweeper games; this
makes the game relatively harder.
.Sh OPTIONS
The following option are used on runtime:
.Bl -tag -width 8n
.It Sy q
quit game
.It Sy w
move up on the Y axis
.It Sy s
move down on the Y axis
.It Sy a
move left on the X axis
.It Sy d
move right on the X axis
.It Sy f
flag cell
.It Sy g
defuse mine (if flagged only)
.It Sy ENTER/o
open cell
.Sh SEE ALSO
.Xr curses 3
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@margiolis.net
