.Dd bf\-VERSION
.Dt BRAINFUCK 1
.Os
.Sh NAME
.Nm bf
.Nd a simple brainfuck interpreter
.Sh SYNOPSIS
.Nm
stdin
.Sh DESCRIPTION
.Nm
reads input from stdin and interprets it
as Brainfuck source code.
.Sh EXAMPLES
To parse a Brainfuck source file
.Pp
.Dl $ bf < src.bf
.Pp
Alternatively, you can pipe to
.Nm
.Pp
.Dl $ cat src.bf | bf
.Pp
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@margiolis.net
